Undid edits
Shrimpstress/cc-tweaked-fabric pull request #44
Opened 2021-04-21 16:12 UTC by 3prm3

## A quick checklist
 - If there's a existing issue, please link to it. If not, provide fill out the same information you would in a normal issue - reproduction steps for bugs, rationale for use-case.
 - If you're working on CraftOS, try to write a few test cases so we can ensure everything continues to work in the future. Tests live in `src/test/resources/test-rom/spec` and can be run with `./gradlew check`.

2021-04-21 16:28 UTC, Devan-Kerman requested changes

2021-04-21 16:28 UTC, Devan-Kerman commented on src/main/resources/assets/computercraft/lua/rom/motd.txt
> +View the source code at https://github.com/3prm3/cc-retweaked
forgot to update that

2021-04-21 16:28 UTC, Devan-Kerman commented on src/main/resources/assets/computercraft/lua/rom/motd.txt
> +Please report issues to https://github.com/3prm3/cc-retweaked/issues
and here

2021-04-21 16:28 UTC, Devan-Kerman commented on src/main/resources/data/computercraft/lua/rom/motd.txt
> +View the documentation at https://tweaked.cc
n here

2021-04-21 16:28 UTC, Devan-Kerman commented on README.md
> +# ![CC: ReTweaked](logo.png)
should be CC:Restitched

2021-04-21 16:28 UTC, Devan-Kerman commented on README.md
> +Bleeding edge builds can be found [here](https://github.com/3prm3/cc-retweaked/actions) at github actions to simplify things
change link

2021-04-21 16:38 UTC, 3prm3 commented on src/main/resources/data/computercraft/lua/rom/motd.txt
> +View the documentation at https://tweaked.cc
wiki.computercraft.cc has been phased out

2021-04-21 16:41 UTC, 3prm3 commented on README.md
> +# ![CC: ReTweaked](logo.png)
this is cc-tweaked

2021-04-21 16:56 UTC, Toad-Dev commented
What is the point of this PR? Outside of the texture changes and some string edits to adventure.lua (are those from upstream of just arbitrary changes?), this PR only contains other PRs that have already been merged (from my repo). 

There are a few new commits from Merith-TK's patchwork project that you pulled, but those could be pulled into here more directly when Merith-TK is ready.

2021-04-21 16:58 UTC, 3prm3 commented
> What is the point of this PR? Outside of the texture changes and some string edits to adventure.lua (are those from upstream of just arbitrary changes?), this PR only contains other PRs that have already been merged (from my repo).
> 
> There are a few new commits from Merith-TK's patchwork project that you pulled, but those could be pulled into here more directly when Merith-TK is ready.

Tweaked some stuff in adventure

2021-04-21 17:00 UTC, 3prm3 commented
i probably will edit more stuff later on

2021-04-21 17:02 UTC, Toad-Dev commented
Is it from upstream (the forge CC: Tweaked project)?

2021-04-21 17:03 UTC, 3prm3 commented
> Is it from upstream (the forge CC: Tweaked project)?

what

2021-04-21 17:07 UTC, 3prm3 commented
Upstream from Merith-TK

2021-04-21 17:08 UTC, 3prm3 commented
Also weirldy enough, my readme has no conflicts,
but Merith-TK's does

2021-04-21 18:06 UTC, Technici4n commented
Are you applying the updates by hand instead of properly merging the relevant commits?

2021-04-21 18:24 UTC, Toad-Dev commented
Yeah these appear to @Merith-TK commits that are copy pasted and recommitted.

2021-04-21 18:25 UTC, 3prm3 commented
> Yeah these appear to @Merith-TK commits that are copy pasted and recommitted.

recently i undid a lot of them

2021-04-21 18:27 UTC, Merith-TK commented
I would request you to stop what you are doing, if you wanted my work added to this repo, you should've requested me to make a PR.

Also, these forks are feature Parity forks. Meaning that they intend to have the features and functions as the mainstream CC:Tweaked.

Any and all changes that are not directly a quilt related bug fix. Are to go to CC:T, not here.

2021-04-21 18:38 UTC, Merith-TK commented
Also. I would appreciate it if you would not steal code I have written for CC:Restiched, and simply rebrand it as your own fork. Also I'm pretty sure that violates liscencing, I may be wrong,

It is still morally unethical to take someone else's work and brand it as your own.

2021-04-21 18:40 UTC, 3prm3 commented
> Also. I would appreciate it if you would not steal code I have written for CC:Restiched, and simply rebrand it as your own fork. Also I'm pretty sure that violates liscencing, I may be wrong,
> 
> It is still morally unethical to take someone else's work and brand it as your own.

i undid that code and sorry

2021-04-21 18:40 UTC, 3prm3 commented
> > Also. I would appreciate it if you would not steal code I have written for CC:Restiched, and simply rebrand it as your own fork. Also I'm pretty sure that violates liscencing, I may be wrong,
> > It is still morally unethical to take someone else's work and brand it as your own.
> 
> i undid that code and sorry for this

2021-04-21 18:40 UTC, 3prm3 commented
https://github.com/3prm3/cc-retweaked/commit/d890bfef0c11cc3581d4bea351f4f95a811956d6

2021-04-21 18:41 UTC, 3prm3 commented
https://github.com/3prm3/cc-retweaked/commit/d5228bde2ff9dbbd9f0e4b8fb2fa72be7070a5ab

2021-04-21 18:41 UTC, 3prm3 commented
ill delete the branch

2021-04-21 18:41 UTC, closed without merging

2021-04-21 18:44 UTC, Merith-TK commented
I would also reccomend learning to use git a bit more before attempting a PR like this.

As with git, if your fork is out of date and you made edits. Odds are, you can merge the latest version with your current version, assuming there are no conflicts in the edits.

2021-04-21 18:45 UTC, 3prm3 commented
> I would also reccomend learning to use git a bit more before attempting a PR like this.
> 
> As with git, if your fork is out of date and you made edits. Odds are, you can merge the latest version with your current version, assuming there are no conflicts in the edits.

thanks

2021-04-21 18:45 UTC, 3prm3 commented
> I would also reccomend learning to use git a bit more before attempting a PR like this.
> 
> As with git, if your fork is out of date and you made edits. Odds are, you can merge the latest version with your current version, assuming there are no conflicts in the edits.

good luck with your fork

2021-04-21 18:47 UTC, 3prm3 commented
> I would also reccomend learning to use git a bit more before attempting a PR like this.
> 
> As with git, if your fork is out of date and you made edits. Odds are, you can merge the latest version with your current version, assuming there are no conflicts in the edits.

nah i use desktop

2021-04-21 18:49 UTC, Merith-TK commented
You need to learn how to use git before contributing to a larger project like this with multiple devs.

Otherwise your PR's won't be accepted. Looking at your commits here, this appears to be a clusterfuck of commits.

2021-04-21 18:50 UTC, Merith-TK commented
Try using Git Kraken. It works well and is what I use for my git code maintenance

2021-04-21 18:50 UTC, 3prm3 commented
> You need to learn how to use git before contributing to a larger project like this with multiple devs.
> 
> Otherwise your PR's won't be accepted. Looking at your commits here, this appears to be a clusterfuck of commits.

ok

2021-04-21 18:51 UTC, 3prm3 commented
> Try using Git Kraken. It works well and is what I use for my git code maintenance

also ill try it

2021-04-21 18:51 UTC, 3prm3 commented
is it this https://www.gitkraken.com/

2021-04-21 18:53 UTC, 3prm3 commented
> I would request you to stop what you are doing, if you wanted my work added to this repo, you should've requested me to make a PR.
> 
> Also, these forks are feature Parity forks. Meaning that they intend to have the features and functions as the mainstream CC:Tweaked.
> 
> Any and all changes that are not directly a quilt related bug fix. Are to go to CC:T, not here.

pr failed cause of some readme thing

2021-04-21 18:54 UTC, 3prm3 commented
also github gave me a "this branch already exsists" error

2021-04-22 06:36 UTC, shedaniel commented
please move elsewhere for the discussion, ill be locking this